---
abstract: 'a map of (bryological) observations'
author:
  - 'Nick Stokoe <wulee@cpan.org>'
build_requires:
  IO::String: 0
  Module::Build: 0.2808
  Pod::Coverage::TrustPod: 0
  SQL::Translator: 0.11018
  Test::DataDirs: 0.001000
configure_requires:
  Module::Build: 0.2808
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MossMap
recommends:
  Test::Pod: 1.14
  Test::Pod::Coverage: 1.04
requires:
  DBIx::Class: 0.08250
  DBIx::Class::Schema::Loader: 0.07036
  JSON::PP: 0
  Module::Build: 0.2808
  Mojolicious: 4.18
  Mojolicious::Plugin::Authentication: 1.25
  Text::CSV: 1.21
resources:
  repository: git://github.com/wu-lee/MossMap.git
version: 0.1.0
